// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Helpi.Domain.ValueObjects;
using Helpi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helpi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921120526_IklklknitialMigrations")]
    partial class IklklknitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpi.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsServiced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Contacts_CityId");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContractNumberSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContractNumberSequences");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreferredNotificationMethod")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyName = "Business and Economics"
                        },
                        new
                        {
                            Id = 2,
                            FacultyName = "Education"
                        },
                        new
                        {
                            Id = 3,
                            FacultyName = "Engineering"
                        },
                        new
                        {
                            Id = 4,
                            FacultyName = "Health Sciences"
                        },
                        new
                        {
                            Id = 5,
                            FacultyName = "Law"
                        },
                        new
                        {
                            Id = 6,
                            FacultyName = "Medicine"
                        },
                        new
                        {
                            Id = 7,
                            FacultyName = "Science"
                        },
                        new
                        {
                            Id = 8,
                            FacultyName = "Social Sciences"
                        },
                        new
                        {
                            Id = 9,
                            FacultyName = "Computer Science"
                        },
                        new
                        {
                            Id = 10,
                            FacultyName = "Arts and Humanities"
                        });
                });

            modelBuilder.Entity("Helpi.Domain.Entities.FcmToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Token");

                    b.ToTable("FcmTokens");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.HNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<int>("RecieverUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeniorId");

                    b.HasIndex("StudentId");

                    b.ToTable("HNotifications");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("MailerliteCampaignId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobInstanceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.InvoiceEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MailerliteMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OpenedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("InvoiceEmails");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CompanyPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("HangFireEndStatusJobId")
                        .HasColumnType("text");

                    b.Property<string>("HangFirePaymentJobId")
                        .HasColumnType("text");

                    b.Property<string>("HangFireStartStatusJobId")
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRescheduleVariant")
                        .HasColumnType("boolean");

                    b.Property<int?>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsSubstitute")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrevAssignmentId")
                        .HasColumnType("integer");

                    b.Property<string>("RescheduleReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RescheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RescheduledFromId")
                        .HasColumnType("integer");

                    b.Property<int?>("RescheduledToId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleAssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceProviderPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("JobInstanceId");

                    b.HasIndex("PrevAssignmentId");

                    b.HasIndex("ScheduleAssignmentId");

                    b.HasIndex("SeniorId");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("IX_JobInstances_OrderStatus");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OrderId", "Status"), new[] { "ScheduledDate" });

                    b.ToTable("JobInstances");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReassignment")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<byte>("PriorityLevel")
                        .HasColumnType("smallint");

                    b.Property<int?>("ReassignAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReassignJobInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReassignmentRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReassignmentType")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderScheduleId");

                    b.HasIndex("ReassignmentRecordId");

                    b.HasIndex("SeniorId");

                    b.HasIndex("StudentId");

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("integer");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SeniorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAutoScheduling")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoScheduleAttemptCount")
                        .HasColumnType("integer");

                    b.Property<int?>("AutoScheduleDisableReason")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_OrderSchedules_Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("DayOfWeek", "StartTime", "EndTime")
                        .HasDatabaseName("IX_OrderSchedules_DayOfWeek_Start_End");

                    b.ToTable("OrderSchedules");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderService", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpiryMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpiryYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcctive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Last4")
                        .HasColumnType("text");

                    b.Property<int>("PaymentProcessor")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessorToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPaymentMethodId")
                        .HasColumnType("text");

                    b.Property<bool>("IsPayoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPayoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MinimaxCustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentProcessor")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredPayoutMethod")
                        .HasColumnType("text");

                    b.Property<string>("StripeConnectAccountId")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentProfiles");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("GatewayId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<JsonDocument>("GatewayResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<byte>("MaxRetries")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessPaymentId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RefundId")
                        .HasColumnType("text");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobInstanceId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PricingChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewCompanyPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NewJobHourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NewServiceProviderPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldCompanyPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldJobHourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldServiceProviderPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("PricingConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PricingChangeHistories");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PricingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompanyPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("JobHourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceProviderPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("PricingConfigurations");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("SeniorFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobInstanceId")
                        .IsUnique();

                    b.HasIndex("SeniorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsJobInstanceSub")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrevAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TerminationReason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderScheduleId");

                    b.HasIndex("StudentId", "OrderScheduleId")
                        .HasDatabaseName("IX_ScheduleAssignments_Student_OrderSchedule");

                    b.ToTable("ScheduleAssignments");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("SpecialRequirements")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Seniors");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, Translation>>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Dictionary<string, Translation>>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CoverageRadiusKm")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CityId", "ServiceId")
                        .IsUnique();

                    b.ToTable("ServiceRegions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("BackgroundCheckDate")
                        .HasColumnType("date");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysToContractExpire")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalRatingSum")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Students_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Students_UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentAvailabilitySlot", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("StudentId", "DayOfWeek");

                    b.HasIndex("StudentId", "DayOfWeek", "StartTime", "EndTime")
                        .HasDatabaseName("IX_AvailabilitySlots_Student_Day_Time");

                    b.ToTable("StudentAvailabilitySlots");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentContracts");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentService", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<byte?>("ExperienceYears")
                        .HasColumnType("smallint");

                    b.HasKey("StudentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StudentId", "ServiceId")
                        .HasDatabaseName("IX_StudentServices_Student_Service");

                    b.ToTable("StudentServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReassignmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAutoScheduling")
                        .HasColumnType("boolean");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentAssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("NewStudentId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginalStudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferredStudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReassignAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReassignJobInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReassignmentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewStudentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderScheduleId");

                    b.HasIndex("OriginalStudentId");

                    b.HasIndex("ReassignAssignmentId");

                    b.HasIndex("ReassignJobInstanceId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("ReassignmentRecords");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Admin")
                        .HasForeignKey("Helpi.Domain.Entities.Admin", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.City", "City")
                        .WithMany("ContactInfos")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Customer")
                        .HasForeignKey("Helpi.Domain.Entities.Customer", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithOne("Customer")
                        .HasForeignKey("Helpi.Domain.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.FcmToken", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithMany("fcmTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpi.Domain.Entities.HNotification", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany()
                        .HasForeignKey("SeniorId");

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Senior");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithMany()
                        .HasForeignKey("JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.PaymentTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobInstance");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.InvoiceEmail", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Invoice", "Invoice")
                        .WithOne("Email")
                        .HasForeignKey("Helpi.Domain.Entities.InvoiceEmail", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.StudentContract", "StudentContract")
                        .WithMany("JobInstances")
                        .HasForeignKey("ContractId");

                    b.HasOne("Helpi.Domain.Entities.JobInstance", null)
                        .WithMany("RescheduledInstances")
                        .HasForeignKey("JobInstanceId");

                    b.HasOne("Helpi.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "PrevAssignment")
                        .WithMany()
                        .HasForeignKey("PrevAssignmentId");

                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "Assignment")
                        .WithMany("JobInstances")
                        .HasForeignKey("ScheduleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany()
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Order");

                    b.Navigation("PrevAssignment");

                    b.Navigation("Senior");

                    b.Navigation("StudentContract");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobRequest", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.OrderSchedule", "OrderSchedule")
                        .WithMany("JobRequests")
                        .HasForeignKey("OrderScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReassignmentRecord", null)
                        .WithMany("JobRequests")
                        .HasForeignKey("ReassignmentRecordId");

                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany()
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderSchedule");

                    b.Navigation("Senior");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany("Orders")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Service", null)
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Order", "Order")
                        .WithMany("Schedules")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderService", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Order", null)
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Customer", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CustomerUserId");

                    b.HasOne("Helpi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentProfile", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.User", "User")
                        .WithMany("PaymentProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("Helpi.Domain.Entities.PaymentTransaction", "JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobInstance");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Review", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithOne("Review")
                        .HasForeignKey("Helpi.Domain.Entities.Review", "JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany()
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobInstance");

                    b.Navigation("Senior");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.OrderSchedule", "OrderSchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("OrderScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("ScheduleAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderSchedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Senior")
                        .HasForeignKey("Helpi.Domain.Entities.Senior", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Customer", null)
                        .WithMany("Seniors")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceRegion", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.City", "City")
                        .WithMany("ServiceRegions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Student")
                        .HasForeignKey("Helpi.Domain.Entities.Student", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithOne("Student")
                        .HasForeignKey("Helpi.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentAvailabilitySlot", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentContract", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("Contracts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentService", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("StudentServices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReassignmentRecord", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Student", "NewStudent")
                        .WithMany()
                        .HasForeignKey("NewStudentId");

                    b.HasOne("Helpi.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.OrderSchedule", "OrderSchedule")
                        .WithMany()
                        .HasForeignKey("OrderScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "OriginalStudent")
                        .WithMany()
                        .HasForeignKey("OriginalStudentId");

                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "ReassignAssignment")
                        .WithMany()
                        .HasForeignKey("ReassignAssignmentId");

                    b.HasOne("Helpi.Domain.Entities.JobInstance", "ReassignJobInstance")
                        .WithMany()
                        .HasForeignKey("ReassignJobInstanceId");

                    b.HasOne("Helpi.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewStudent");

                    b.Navigation("Order");

                    b.Navigation("OrderSchedule");

                    b.Navigation("OriginalStudent");

                    b.Navigation("ReassignAssignment");

                    b.Navigation("ReassignJobInstance");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.City", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("ServiceRegions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Senior")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Seniors");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Email");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.Navigation("PaymentTransaction");

                    b.Navigation("RescheduledInstances");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderServices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("JobRequests");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.Navigation("JobInstances");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Contracts");

                    b.Navigation("ScheduleAssignments");

                    b.Navigation("StudentServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentContract", b =>
                {
                    b.Navigation("JobInstances");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("PaymentProfiles");

                    b.Navigation("Student");

                    b.Navigation("fcmTokens");
                });

            modelBuilder.Entity("ReassignmentRecord", b =>
                {
                    b.Navigation("JobRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
