// <auto-generated />
using System;
using System.Text.Json;
using Helpi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helpi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpi.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Polygon>("Bounds")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsServiced")
                        .HasColumnType("boolean");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Bounds");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Bounds"), "GIST");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredNotificationMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyName = "Business and Economics"
                        },
                        new
                        {
                            Id = 2,
                            FacultyName = "Education"
                        },
                        new
                        {
                            Id = 3,
                            FacultyName = "Engineering"
                        },
                        new
                        {
                            Id = 4,
                            FacultyName = "Health Sciences"
                        },
                        new
                        {
                            Id = 5,
                            FacultyName = "Law"
                        },
                        new
                        {
                            Id = 6,
                            FacultyName = "Medicine"
                        },
                        new
                        {
                            Id = 7,
                            FacultyName = "Science"
                        },
                        new
                        {
                            Id = 8,
                            FacultyName = "Social Sciences"
                        },
                        new
                        {
                            Id = 9,
                            FacultyName = "Computer Science"
                        },
                        new
                        {
                            Id = 10,
                            FacultyName = "Arts and Humanities"
                        });
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("MailerliteCampaignId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobInstanceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.InvoiceEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MailerliteMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OpenedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("InvoiceEmails");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("OriginalAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleAssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubstitutionStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginalAssignmentId");

                    b.HasIndex("ScheduleAssignmentId");

                    b.ToTable("JobInstances");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmergencySub")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<byte>("PriorityLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("integer");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeniorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderSchedules");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("Processor")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("GatewayId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<JsonDocument>("GatewayResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<byte>("MaxRetries")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobInstanceId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobInstanceId")
                        .HasColumnType("integer");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("SeniorId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobInstanceId")
                        .IsUnique();

                    b.HasIndex("SeniorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TerminationReason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("ScheduleAssignments");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignmentReplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("NewAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalAssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReplacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacementReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewAssignmentId");

                    b.HasIndex("OriginalAssignmentId");

                    b.ToTable("ScheduleAssignmentReplacements");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("SpecialRequirements")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Seniors");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<short>("MinDuration")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CoverageRadiusKm")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CityId", "ServiceId")
                        .IsUnique();

                    b.ToTable("ServiceRegions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("BackgroundCheckDate")
                        .HasColumnType("date");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentAvailabilitySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAvailabilitySlots");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentContracts");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentService", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<byte?>("ExperienceYears")
                        .HasColumnType("smallint");

                    b.HasKey("StudentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("StudentServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.City", "CityNavigation")
                        .WithMany("ContactInfos")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityNavigation");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Customer")
                        .HasForeignKey("Helpi.Domain.Entities.Customer", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Helpi.Domain.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithMany()
                        .HasForeignKey("JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.PaymentTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobInstance");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.InvoiceEmail", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Invoice", "Invoice")
                        .WithOne("Email")
                        .HasForeignKey("Helpi.Domain.Entities.InvoiceEmail", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "OriginalAssignment")
                        .WithMany()
                        .HasForeignKey("OriginalAssignmentId");

                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "Assignment")
                        .WithMany("JobInstances")
                        .HasForeignKey("ScheduleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("OriginalAssignment");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobRequest", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.OrderSchedule", "OrderSchedule")
                        .WithMany("JobRequests")
                        .HasForeignKey("OrderScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderSchedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany("Orders")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Senior");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Order", "Order")
                        .WithMany("Schedules")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Customer", "Customer")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("Helpi.Domain.Entities.PaymentTransaction", "JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobInstance");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Review", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.JobInstance", "JobInstance")
                        .WithOne("Review")
                        .HasForeignKey("Helpi.Domain.Entities.Review", "JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Senior", "Senior")
                        .WithMany()
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobInstance");

                    b.Navigation("Senior");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.OrderSchedule", "OrderSchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("OrderScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderSchedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignmentReplacement", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "NewAssignment")
                        .WithMany()
                        .HasForeignKey("NewAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.ScheduleAssignment", "OriginalAssignment")
                        .WithMany()
                        .HasForeignKey("OriginalAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewAssignment");

                    b.Navigation("OriginalAssignment");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Senior")
                        .HasForeignKey("Helpi.Domain.Entities.Senior", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Customer", "Customer")
                        .WithMany("Seniors")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceRegion", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.City", "City")
                        .WithMany("ServiceRegions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.ContactInfo", "Contact")
                        .WithOne("Student")
                        .HasForeignKey("Helpi.Domain.Entities.Student", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Helpi.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentAvailabilitySlot", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentContract", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.StudentService", b =>
                {
                    b.HasOne("Helpi.Domain.Entities.Service", "Service")
                        .WithMany("StudentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpi.Domain.Entities.Student", "Student")
                        .WithMany("StudentServices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.City", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("ServiceRegions");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ContactInfo", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Senior")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Customer", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Seniors");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Email");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.JobInstance", b =>
                {
                    b.Navigation("PaymentTransaction");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Order", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.OrderSchedule", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("JobRequests");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ScheduleAssignment", b =>
                {
                    b.Navigation("JobInstances");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Senior", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Service", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("StudentServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.Student", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("StudentServices");
                });

            modelBuilder.Entity("Helpi.Domain.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
