CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserType" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GooglePlaceId" character varying(255) NOT NULL,
    "Name" character varying(255) NOT NULL,
    "PostalCode" text NOT NULL,
    "IsServiced" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
);

CREATE TABLE "ContractNumberSequences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NextNumber" integer NOT NULL,
    CONSTRAINT "PK_ContractNumberSequences" PRIMARY KEY ("Id")
);

CREATE TABLE "Faculties" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FacultyName" character varying(100) NOT NULL,
    CONSTRAINT "PK_Faculties" PRIMARY KEY ("Id")
);

CREATE TABLE "PricingChangeHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PricingConfigurationId" integer NOT NULL,
    "OldJobHourlyRate" numeric NOT NULL,
    "OldCompanyPercentage" numeric NOT NULL,
    "OldServiceProviderPercentage" numeric NOT NULL,
    "NewJobHourlyRate" numeric NOT NULL,
    "NewCompanyPercentage" numeric NOT NULL,
    "NewServiceProviderPercentage" numeric NOT NULL,
    "ChangeDate" timestamp with time zone NOT NULL,
    "ChangedBy" integer NOT NULL,
    "Reason" text,
    CONSTRAINT "PK_PricingChangeHistories" PRIMARY KEY ("Id")
);

CREATE TABLE "PricingConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobHourlyRate" numeric(18,2) NOT NULL,
    "CompanyPercentage" numeric(5,2) NOT NULL,
    "ServiceProviderPercentage" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_PricingConfigurations" PRIMARY KEY ("Id")
);

CREATE TABLE "ServiceCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeletedOn" timestamp with time zone,
    "Translations" jsonb NOT NULL,
    "Icon" character varying(50),
    CONSTRAINT "PK_ServiceCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FcmTokens" (
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    CONSTRAINT "PK_FcmTokens" PRIMARY KEY ("UserId", "Token"),
    CONSTRAINT "FK_FcmTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PaymentProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "MinimaxCustomerId" integer,
    "PaymentProcessor" integer NOT NULL,
    "StripeCustomerId" text,
    "StripeConnectAccountId" text,
    "IsPayoutEnabled" boolean NOT NULL,
    "LastPayoutDate" timestamp with time zone,
    "DefaultPaymentMethodId" text,
    "PreferredPayoutMethod" text,
    CONSTRAINT "PK_PaymentProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactInfos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(255) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "Email" text,
    "Gender" integer NOT NULL,
    "GooglePlaceId" character varying(255) NOT NULL,
    "FullAddress" text NOT NULL,
    "Latitude" numeric NOT NULL,
    "Longitude" numeric NOT NULL,
    "CityId" integer NOT NULL,
    "CityName" text NOT NULL,
    "State" text,
    "PostalCode" character varying(20),
    "Country" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ContactInfos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactInfos_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" integer NOT NULL,
    "DeletedOn" timestamp with time zone,
    "Translations" jsonb NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Services_ServiceCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ServiceCategories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Admin" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContactId" integer NOT NULL,
    CONSTRAINT "PK_Admin" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Admin_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Customers" (
    "UserId" integer NOT NULL,
    "ContactId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PreferredNotificationMethod" integer NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Customers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Customers_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Students" (
    "UserId" integer NOT NULL,
    "StudentNumber" character varying(20) NOT NULL,
    "FacultyId" integer NOT NULL,
    "DateRegistered" timestamp with time zone NOT NULL,
    "ContactId" integer NOT NULL,
    "Status" integer NOT NULL,
    "DaysToContractExpire" integer,
    "DeletedOn" timestamp with time zone,
    "BackgroundCheckDate" date,
    "TotalReviews" integer NOT NULL,
    "TotalRatingSum" numeric NOT NULL,
    "AverageRating" numeric NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Students_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Students_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Students_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServiceRegions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CityId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CoverageRadiusKm" integer NOT NULL,
    CONSTRAINT "PK_ServiceRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceRegions_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ServiceRegions_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PaymentMethods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Brand" text,
    "Last4" text,
    "ExpiryMonth" integer,
    "ExpiryYear" integer,
    "PaymentProcessor" integer NOT NULL,
    "ProcessorToken" text,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsAcctive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CustomerUserId" integer,
    CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentMethods_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentMethods_Customers_CustomerUserId" FOREIGN KEY ("CustomerUserId") REFERENCES "Customers" ("UserId")
);

CREATE TABLE "Seniors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "ContactId" integer NOT NULL,
    "Relationship" integer NOT NULL,
    "SpecialRequirements" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Seniors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Seniors_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Seniors_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "StudentAvailabilitySlots" (
    "StudentId" integer NOT NULL,
    "DayOfWeek" smallint NOT NULL,
    "StartTime" time NOT NULL,
    "EndTime" time NOT NULL,
    CONSTRAINT "PK_StudentAvailabilitySlots" PRIMARY KEY ("StudentId", "DayOfWeek"),
    CONSTRAINT "FK_StudentAvailabilitySlots_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "StudentContracts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" integer NOT NULL,
    "DeletedOn" timestamp with time zone,
    "ContractNumber" text NOT NULL,
    "CloudPath" character varying(512) NOT NULL,
    "EffectiveDate" date NOT NULL,
    "ExpirationDate" date NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudentContracts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentContracts_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "StudentServices" (
    "StudentId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "ExperienceYears" smallint,
    CONSTRAINT "PK_StudentServices" PRIMARY KEY ("StudentId", "ServiceId"),
    CONSTRAINT "FK_StudentServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentServices_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "HNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RecieverUserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "Payload" text,
    "StudentId" integer,
    "SeniorId" integer,
    CONSTRAINT "PK_HNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HNotifications_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id"),
    CONSTRAINT "FK_HNotifications_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId")
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SeniorId" integer NOT NULL,
    "Status" integer NOT NULL,
    "IsRecurring" boolean NOT NULL,
    "PaymentMethodId" integer,
    "RecurrencePattern" integer,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "CancelledAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ServiceId" integer,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id"),
    CONSTRAINT "FK_Orders_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id")
);

CREATE TABLE "OrderSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "DayOfWeek" smallint NOT NULL,
    "StartTime" time NOT NULL,
    "EndTime" time NOT NULL,
    "IsCancelled" boolean NOT NULL,
    "AutoScheduleAttemptCount" integer NOT NULL,
    "AllowAutoScheduling" boolean NOT NULL,
    "AutoScheduleDisableReason" integer,
    "CancellationReason" text,
    CONSTRAINT "PK_OrderSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderSchedules_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderServices" (
    "OrderId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    CONSTRAINT "PK_OrderServices" PRIMARY KEY ("OrderId", "ServiceId"),
    CONSTRAINT "FK_OrderServices_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScheduleAssignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderScheduleId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "Status" integer NOT NULL,
    "IsJobInstanceSub" boolean NOT NULL,
    "PrevAssignmentId" integer,
    "TerminationReason" integer,
    "TerminatedAt" timestamp with time zone,
    "AssignedAt" timestamp with time zone NOT NULL,
    "AcceptedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_ScheduleAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleAssignments_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleAssignments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "JobInstances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SeniorId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "OrderScheduleId" integer NOT NULL,
    "ContractId" integer,
    "ScheduleAssignmentId" integer NOT NULL,
    "PrevAssignmentId" integer,
    "ScheduledDate" date NOT NULL,
    "StartTime" time NOT NULL,
    "EndTime" time NOT NULL,
    "Status" integer NOT NULL,
    "NeedsSubstitute" boolean NOT NULL,
    "ActualStartTime" timestamp with time zone,
    "ActualEndTime" timestamp with time zone,
    "IsRescheduleVariant" boolean NOT NULL,
    "RescheduledFromId" integer,
    "RescheduledToId" integer,
    "RescheduledAt" timestamp with time zone,
    "RescheduleReason" text,
    "HourlyRate" numeric(18,2) NOT NULL,
    "CompanyPercentage" numeric(5,2) NOT NULL,
    "ServiceProviderPercentage" numeric(5,2) NOT NULL,
    "HangFireStartStatusJobId" text,
    "HangFireEndStatusJobId" text,
    "HangFirePaymentJobId" text,
    "JobInstanceId" integer,
    CONSTRAINT "PK_JobInstances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobInstances_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id"),
    CONSTRAINT "FK_JobInstances_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobInstances_ScheduleAssignments_PrevAssignmentId" FOREIGN KEY ("PrevAssignmentId") REFERENCES "ScheduleAssignments" ("Id"),
    CONSTRAINT "FK_JobInstances_ScheduleAssignments_ScheduleAssignmentId" FOREIGN KEY ("ScheduleAssignmentId") REFERENCES "ScheduleAssignments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobInstances_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobInstances_StudentContracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "StudentContracts" ("Id")
);

CREATE TABLE "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "JobInstanceId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "PaymentMethodId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "ScheduledAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "NextRetryAt" timestamp with time zone,
    "Status" integer NOT NULL,
    "RetryCount" smallint NOT NULL,
    "MaxRetries" smallint NOT NULL,
    "ProcessPaymentId" text,
    "GatewayId" character varying(255),
    "GatewayResponse" jsonb,
    "IdempotencyKey" character varying(64),
    "RefundId" text,
    "RefundReason" text,
    "RefundAmount" numeric,
    "RefundedAt" timestamp with time zone,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentTransactions_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReassignmentRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReassignJobInstanceId" integer,
    "ReassignAssignmentId" integer,
    "CurrentAssignmentId" integer NOT NULL,
    "OrderScheduleId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "ReassignmentType" integer NOT NULL,
    "Trigger" integer NOT NULL,
    "Reason" text NOT NULL,
    "AllowAutoScheduling" boolean NOT NULL,
    "Status" integer NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "RequestedByUserId" integer NOT NULL,
    "OriginalStudentId" integer,
    "NewStudentId" integer,
    "AttemptCount" integer NOT NULL,
    "MaxAttempts" integer NOT NULL,
    "LastAttemptAt" timestamp with time zone,
    "PreferredStudentId" integer,
    CONSTRAINT "PK_ReassignmentRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReassignmentRecords_AspNetUsers_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReassignmentRecords_JobInstances_ReassignJobInstanceId" FOREIGN KEY ("ReassignJobInstanceId") REFERENCES "JobInstances" ("Id"),
    CONSTRAINT "FK_ReassignmentRecords_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReassignmentRecords_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReassignmentRecords_ScheduleAssignments_ReassignAssignmentId" FOREIGN KEY ("ReassignAssignmentId") REFERENCES "ScheduleAssignments" ("Id"),
    CONSTRAINT "FK_ReassignmentRecords_Students_NewStudentId" FOREIGN KEY ("NewStudentId") REFERENCES "Students" ("UserId"),
    CONSTRAINT "FK_ReassignmentRecords_Students_OriginalStudentId" FOREIGN KEY ("OriginalStudentId") REFERENCES "Students" ("UserId")
);

CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SeniorId" integer NOT NULL,
    "SeniorFullName" text NOT NULL,
    "StudentId" integer NOT NULL,
    "StudentFullName" text NOT NULL,
    "JobInstanceId" integer NOT NULL,
    "Rating" smallint NOT NULL,
    "Comment" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Invoices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobInstanceId" integer NOT NULL,
    "TransactionId" integer NOT NULL,
    "MailerliteCampaignId" character varying(255),
    "InvoiceNumber" character varying(50) NOT NULL,
    "Status" integer NOT NULL,
    "DueDate" date NOT NULL,
    "SentAt" timestamp with time zone,
    "ViewedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invoices_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Invoices_PaymentTransactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "PaymentTransactions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "JobRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderScheduleId" integer NOT NULL,
    "JobInstanceId" integer,
    "StudentId" integer NOT NULL,
    "SeniorId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "Status" integer NOT NULL,
    "RespondedAt" timestamp with time zone,
    "RejectionReason" text,
    "SentAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "PriorityLevel" smallint NOT NULL,
    "IsReassignment" boolean NOT NULL,
    "ReassignmentRecordId" integer,
    "ReassignmentType" integer,
    "ReassignAssignmentId" integer,
    "ReassignJobInstanceId" integer,
    CONSTRAINT "PK_JobRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobRequests_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id"),
    CONSTRAINT "FK_JobRequests_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobRequests_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobRequests_ReassignmentRecords_ReassignmentRecordId" FOREIGN KEY ("ReassignmentRecordId") REFERENCES "ReassignmentRecords" ("Id"),
    CONSTRAINT "FK_JobRequests_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobRequests_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "InvoiceEmails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "MailerliteMessageId" character varying(255),
    "Status" integer NOT NULL,
    "OpenedCount" integer NOT NULL,
    "LastAttempt" timestamp with time zone,
    "AttemptCount" integer NOT NULL,
    "ErrorMessage" text,
    CONSTRAINT "PK_InvoiceEmails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceEmails_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (1, 'Business and Economics');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (2, 'Education');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (3, 'Engineering');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (4, 'Health Sciences');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (5, 'Law');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (6, 'Medicine');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (7, 'Science');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (8, 'Social Sciences');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (9, 'Computer Science');
INSERT INTO "Faculties" ("Id", "FacultyName")
VALUES (10, 'Arts and Humanities');

CREATE UNIQUE INDEX "IX_Admin_ContactId" ON "Admin" ("ContactId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Cities_GooglePlaceId" ON "Cities" ("GooglePlaceId");

CREATE INDEX "IX_Contacts_CityId" ON "ContactInfos" ("CityId");

CREATE UNIQUE INDEX "IX_Customers_ContactId" ON "Customers" ("ContactId");

CREATE INDEX "IX_HNotifications_SeniorId" ON "HNotifications" ("SeniorId");

CREATE INDEX "IX_HNotifications_StudentId" ON "HNotifications" ("StudentId");

CREATE UNIQUE INDEX "IX_InvoiceEmails_InvoiceId" ON "InvoiceEmails" ("InvoiceId");

CREATE INDEX "IX_Invoices_JobInstanceId" ON "Invoices" ("JobInstanceId");

CREATE INDEX "IX_Invoices_TransactionId" ON "Invoices" ("TransactionId");

CREATE INDEX "IX_JobInstances_ContractId" ON "JobInstances" ("ContractId");

CREATE INDEX "IX_JobInstances_JobInstanceId" ON "JobInstances" ("JobInstanceId");

CREATE INDEX "IX_JobInstances_OrderStatus" ON "JobInstances" ("OrderId", "Status") INCLUDE ("ScheduledDate");

CREATE INDEX "IX_JobInstances_PrevAssignmentId" ON "JobInstances" ("PrevAssignmentId");

CREATE INDEX "IX_JobInstances_ScheduleAssignmentId" ON "JobInstances" ("ScheduleAssignmentId");

CREATE INDEX "IX_JobInstances_SeniorId" ON "JobInstances" ("SeniorId");

CREATE INDEX "IX_JobRequests_JobInstanceId" ON "JobRequests" ("JobInstanceId");

CREATE INDEX "IX_JobRequests_OrderId" ON "JobRequests" ("OrderId");

CREATE INDEX "IX_JobRequests_OrderScheduleId" ON "JobRequests" ("OrderScheduleId");

CREATE INDEX "IX_JobRequests_ReassignmentRecordId" ON "JobRequests" ("ReassignmentRecordId");

CREATE INDEX "IX_JobRequests_SeniorId" ON "JobRequests" ("SeniorId");

CREATE INDEX "IX_JobRequests_StudentId" ON "JobRequests" ("StudentId");

CREATE INDEX "IX_Orders_PaymentMethodId" ON "Orders" ("PaymentMethodId");

CREATE INDEX "IX_Orders_SeniorId" ON "Orders" ("SeniorId");

CREATE INDEX "IX_Orders_ServiceId" ON "Orders" ("ServiceId");

CREATE INDEX "IX_OrderSchedules_DayOfWeek_Start_End" ON "OrderSchedules" ("DayOfWeek", "StartTime", "EndTime");

CREATE INDEX "IX_OrderSchedules_Id" ON "OrderSchedules" ("Id");

CREATE INDEX "IX_OrderSchedules_OrderId" ON "OrderSchedules" ("OrderId");

CREATE INDEX "IX_OrderServices_ServiceId" ON "OrderServices" ("ServiceId");

CREATE INDEX "IX_PaymentMethods_CustomerUserId" ON "PaymentMethods" ("CustomerUserId");

CREATE INDEX "IX_PaymentMethods_UserId" ON "PaymentMethods" ("UserId");

CREATE INDEX "IX_PaymentProfiles_UserId" ON "PaymentProfiles" ("UserId");

CREATE INDEX "IX_PaymentTransactions_CustomerId" ON "PaymentTransactions" ("CustomerId");

CREATE UNIQUE INDEX "IX_PaymentTransactions_JobInstanceId" ON "PaymentTransactions" ("JobInstanceId");

CREATE INDEX "IX_PaymentTransactions_PaymentMethodId" ON "PaymentTransactions" ("PaymentMethodId");

CREATE INDEX "IX_ReassignmentRecords_NewStudentId" ON "ReassignmentRecords" ("NewStudentId");

CREATE INDEX "IX_ReassignmentRecords_OrderId" ON "ReassignmentRecords" ("OrderId");

CREATE INDEX "IX_ReassignmentRecords_OrderScheduleId" ON "ReassignmentRecords" ("OrderScheduleId");

CREATE INDEX "IX_ReassignmentRecords_OriginalStudentId" ON "ReassignmentRecords" ("OriginalStudentId");

CREATE INDEX "IX_ReassignmentRecords_ReassignAssignmentId" ON "ReassignmentRecords" ("ReassignAssignmentId");

CREATE INDEX "IX_ReassignmentRecords_ReassignJobInstanceId" ON "ReassignmentRecords" ("ReassignJobInstanceId");

CREATE INDEX "IX_ReassignmentRecords_RequestedByUserId" ON "ReassignmentRecords" ("RequestedByUserId");

CREATE UNIQUE INDEX "IX_Reviews_JobInstanceId" ON "Reviews" ("JobInstanceId");

CREATE INDEX "IX_Reviews_SeniorId" ON "Reviews" ("SeniorId");

CREATE INDEX "IX_Reviews_StudentId" ON "Reviews" ("StudentId");

CREATE INDEX "IX_ScheduleAssignments_OrderScheduleId" ON "ScheduleAssignments" ("OrderScheduleId");

CREATE INDEX "IX_ScheduleAssignments_Student_OrderSchedule" ON "ScheduleAssignments" ("StudentId", "OrderScheduleId");

CREATE UNIQUE INDEX "IX_Seniors_ContactId" ON "Seniors" ("ContactId");

CREATE INDEX "IX_Seniors_CustomerId" ON "Seniors" ("CustomerId");

CREATE UNIQUE INDEX "IX_ServiceRegions_CityId_ServiceId" ON "ServiceRegions" ("CityId", "ServiceId");

CREATE INDEX "IX_ServiceRegions_ServiceId" ON "ServiceRegions" ("ServiceId");

CREATE INDEX "IX_Services_CategoryId" ON "Services" ("CategoryId");

CREATE INDEX "IX_AvailabilitySlots_Student_Day_Time" ON "StudentAvailabilitySlots" ("StudentId", "DayOfWeek", "StartTime", "EndTime");

CREATE INDEX "IX_StudentContracts_StudentId" ON "StudentContracts" ("StudentId");

CREATE UNIQUE INDEX "IX_Students_ContactId" ON "Students" ("ContactId");

CREATE INDEX "IX_Students_FacultyId" ON "Students" ("FacultyId");

CREATE INDEX "IX_Students_Status" ON "Students" ("Status");

CREATE INDEX "IX_Students_UserId" ON "Students" ("UserId");

CREATE INDEX "IX_StudentServices_ServiceId" ON "StudentServices" ("ServiceId");

CREATE INDEX "IX_StudentServices_Student_Service" ON "StudentServices" ("StudentId", "ServiceId");

SELECT setval(
    pg_get_serial_sequence('"Faculties"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Faculties") + 1,
        nextval(pg_get_serial_sequence('"Faculties"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250924075121_InitialMigrations', '9.0.2');

COMMIT;

