CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserType" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Cities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "GooglePlaceId" character varying(255) NOT NULL,
        "Name" character varying(255) NOT NULL,
        "PostalCode" text NOT NULL,
        "IsServiced" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ContractNumberSequences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NextNumber" integer NOT NULL,
        CONSTRAINT "PK_ContractNumberSequences" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Faculties" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FacultyName" character varying(100) NOT NULL,
        CONSTRAINT "PK_Faculties" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "InvoiceEmails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalInvoiceId" integer NOT NULL,
        "Type" integer NOT NULL,
        "Status" integer NOT NULL,
        "OpenedCount" integer NOT NULL,
        "LastAttempt" timestamp with time zone,
        "NextAttempt" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "ErrorMessage" text,
        CONSTRAINT "PK_InvoiceEmails" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PasswordResetCodes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "Code" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Used" boolean NOT NULL,
        CONSTRAINT "PK_PasswordResetCodes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PricingChangeHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PricingConfigurationId" integer NOT NULL,
        "OldJobHourlyRate" numeric NOT NULL,
        "OldCompanyPercentage" numeric NOT NULL,
        "OldServiceProviderPercentage" numeric NOT NULL,
        "NewJobHourlyRate" numeric NOT NULL,
        "NewCompanyPercentage" numeric NOT NULL,
        "NewServiceProviderPercentage" numeric NOT NULL,
        "ChangeDate" timestamp with time zone NOT NULL,
        "ChangedBy" integer NOT NULL,
        "Reason" text,
        CONSTRAINT "PK_PricingChangeHistories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PricingConfigurations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobHourlyRate" numeric(18,2) NOT NULL,
        "CompanyPercentage" numeric(5,2) NOT NULL,
        "ServiceProviderPercentage" numeric(5,2) NOT NULL,
        CONSTRAINT "PK_PricingConfigurations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ServiceCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DeletedOn" timestamp with time zone,
        "Translations" jsonb NOT NULL,
        "Icon" character varying(400),
        CONSTRAINT "PK_ServiceCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "FcmTokens" (
        "UserId" integer NOT NULL,
        "Token" text NOT NULL,
        CONSTRAINT "PK_FcmTokens" PRIMARY KEY ("UserId", "Token"),
        CONSTRAINT "FK_FcmTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PaymentProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "MinimaxCustomerId" integer,
        "PaymentProcessor" integer NOT NULL,
        "StripeCustomerId" text,
        "StripeConnectAccountId" text,
        "IsPayoutEnabled" boolean NOT NULL,
        "LastPayoutDate" timestamp with time zone,
        "DefaultPaymentMethodId" text,
        "PreferredPayoutMethod" text,
        CONSTRAINT "PK_PaymentProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ContactInfos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(255) NOT NULL,
        "DateOfBirth" date NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Email" text,
        "Gender" integer NOT NULL,
        "GooglePlaceId" character varying(255) NOT NULL,
        "FullAddress" text NOT NULL,
        "Latitude" numeric NOT NULL,
        "Longitude" numeric NOT NULL,
        "CityId" integer NOT NULL,
        "CityName" text NOT NULL,
        "State" text,
        "PostalCode" character varying(20),
        "Country" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactInfos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContactInfos_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Services" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CategoryId" integer NOT NULL,
        "DeletedOn" timestamp with time zone,
        "Translations" jsonb NOT NULL,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Services_ServiceCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ServiceCategories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Admin" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContactId" integer NOT NULL,
        CONSTRAINT "PK_Admin" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Admin_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Customers" (
        "UserId" integer NOT NULL,
        "ContactId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "PreferredNotificationMethod" integer NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Customers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Customers_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Students" (
        "UserId" integer NOT NULL,
        "StudentNumber" character varying(20) NOT NULL,
        "FacultyId" integer NOT NULL,
        "DateRegistered" timestamp with time zone NOT NULL,
        "ContactId" integer NOT NULL,
        "Status" integer NOT NULL,
        "DaysToContractExpire" integer,
        "DeletedOn" timestamp with time zone,
        "BackgroundCheckDate" date,
        "TotalReviews" integer NOT NULL,
        "TotalRatingSum" numeric NOT NULL,
        "AverageRating" numeric NOT NULL,
        CONSTRAINT "PK_Students" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Students_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Students_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Students_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ServiceRegions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CityId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "Active" boolean NOT NULL,
        "CoverageRadiusKm" integer NOT NULL,
        CONSTRAINT "PK_ServiceRegions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceRegions_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ServiceRegions_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PaymentMethods" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Brand" text,
        "Last4" text,
        "ExpiryMonth" integer,
        "ExpiryYear" integer,
        "PaymentProcessor" integer NOT NULL,
        "ProcessorToken" text,
        "IsDefault" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsAcctive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CustomerUserId" integer,
        CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentMethods_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PaymentMethods_Customers_CustomerUserId" FOREIGN KEY ("CustomerUserId") REFERENCES "Customers" ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Seniors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ContactId" integer NOT NULL,
        "Relationship" integer NOT NULL,
        "SpecialRequirements" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Seniors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Seniors_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Seniors_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "StudentAvailabilitySlots" (
        "StudentId" integer NOT NULL,
        "DayOfWeek" smallint NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        CONSTRAINT "PK_StudentAvailabilitySlots" PRIMARY KEY ("StudentId", "DayOfWeek"),
        CONSTRAINT "FK_StudentAvailabilitySlots_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "StudentContracts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentId" integer NOT NULL,
        "DeletedOn" timestamp with time zone,
        "ContractNumber" text NOT NULL,
        "CloudPath" character varying(512) NOT NULL,
        "EffectiveDate" date NOT NULL,
        "ExpirationDate" date NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StudentContracts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StudentContracts_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "StudentServices" (
        "StudentId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "ExperienceYears" smallint,
        CONSTRAINT "PK_StudentServices" PRIMARY KEY ("StudentId", "ServiceId"),
        CONSTRAINT "FK_StudentServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StudentServices_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "HNotifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RecieverUserId" integer NOT NULL,
        "Title" text NOT NULL,
        "Body" text NOT NULL,
        "Type" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsRead" boolean NOT NULL,
        "Payload" text,
        "StudentId" integer,
        "SeniorId" integer,
        CONSTRAINT "PK_HNotifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HNotifications_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id"),
        CONSTRAINT "FK_HNotifications_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SeniorId" integer NOT NULL,
        "Status" integer NOT NULL,
        "IsRecurring" boolean NOT NULL,
        "PaymentMethodId" integer,
        "RecurrencePattern" integer,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "Notes" character varying(1000),
        "CancelledAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "HangFireMatchingJobId" text,
        "ServiceId" integer,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id"),
        CONSTRAINT "FK_Orders_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "OrderSchedules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "DayOfWeek" smallint NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        "IsCancelled" boolean NOT NULL,
        "AutoScheduleAttemptCount" integer NOT NULL,
        "AllowAutoScheduling" boolean NOT NULL,
        "AutoScheduleDisableReason" integer,
        "CancellationReason" text,
        CONSTRAINT "PK_OrderSchedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderSchedules_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "OrderServices" (
        "OrderId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        CONSTRAINT "PK_OrderServices" PRIMARY KEY ("OrderId", "ServiceId"),
        CONSTRAINT "FK_OrderServices_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ScheduleAssignments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderScheduleId" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "StudentId" integer NOT NULL,
        "Status" integer NOT NULL,
        "IsJobInstanceSub" boolean NOT NULL,
        "PrevAssignmentId" integer,
        "TerminationReason" integer,
        "TerminatedAt" timestamp with time zone,
        "AssignedAt" timestamp with time zone NOT NULL,
        "AcceptedAt" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_ScheduleAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ScheduleAssignments_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ScheduleAssignments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "JobInstances" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SeniorId" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "Notes" character varying(1000),
        "OrderScheduleId" integer NOT NULL,
        "ContractId" integer,
        "ScheduleAssignmentId" integer NOT NULL,
        "PrevAssignmentId" integer,
        "ScheduledDate" date NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        "Status" integer NOT NULL,
        "NeedsSubstitute" boolean NOT NULL,
        "ActualStartTime" timestamp with time zone,
        "ActualEndTime" timestamp with time zone,
        "IsRescheduleVariant" boolean NOT NULL,
        "RescheduledFromId" integer,
        "RescheduledToId" integer,
        "RescheduledAt" timestamp with time zone,
        "RescheduleReason" text,
        "HourlyRate" numeric(18,2) NOT NULL,
        "CompanyPercentage" numeric(5,2) NOT NULL,
        "ServiceProviderPercentage" numeric(5,2) NOT NULL,
        "PaymentTransactionId" integer,
        "PaymentStatus" integer NOT NULL,
        "HangFireStartStatusJobId" text,
        "HangFireEndStatusJobId" text,
        "HangFirePaymentJobId" text,
        "HangFireRemindStudentJobId" text,
        "JobInstanceId" integer,
        CONSTRAINT "PK_JobInstances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobInstances_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id"),
        CONSTRAINT "FK_JobInstances_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobInstances_ScheduleAssignments_PrevAssignmentId" FOREIGN KEY ("PrevAssignmentId") REFERENCES "ScheduleAssignments" ("Id"),
        CONSTRAINT "FK_JobInstances_ScheduleAssignments_ScheduleAssignmentId" FOREIGN KEY ("ScheduleAssignmentId") REFERENCES "ScheduleAssignments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobInstances_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobInstances_StudentContracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "StudentContracts" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "PaymentTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "JobInstanceId" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        "PaymentMethodId" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "ScheduledAt" timestamp with time zone NOT NULL,
        "ProcessedAt" timestamp with time zone,
        "NextRetryAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "RetryCount" smallint NOT NULL,
        "MaxRetries" smallint NOT NULL,
        "ProcessPaymentId" text,
        "GatewayId" character varying(255),
        "GatewayResponse" jsonb,
        "IdempotencyKey" character varying(64),
        "RefundId" text,
        "RefundReason" text,
        "RefundAmount" numeric,
        "RefundedAt" timestamp with time zone,
        CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentTransactions_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("UserId") ON DELETE CASCADE,
        CONSTRAINT "FK_PaymentTransactions_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PaymentTransactions_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "ReassignmentRecords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReassignJobInstanceId" integer,
        "ReassignAssignmentId" integer,
        "CurrentAssignmentId" integer NOT NULL,
        "OrderScheduleId" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "ReassignmentType" integer NOT NULL,
        "Trigger" integer NOT NULL,
        "Reason" text NOT NULL,
        "AllowAutoScheduling" boolean NOT NULL,
        "Status" integer NOT NULL,
        "RequestedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "RequestedByUserId" integer NOT NULL,
        "OriginalStudentId" integer,
        "NewStudentId" integer,
        "AttemptCount" integer NOT NULL,
        "MaxAttempts" integer NOT NULL,
        "LastAttemptAt" timestamp with time zone,
        "PreferredStudentId" integer,
        CONSTRAINT "PK_ReassignmentRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReassignmentRecords_AspNetUsers_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ReassignmentRecords_JobInstances_ReassignJobInstanceId" FOREIGN KEY ("ReassignJobInstanceId") REFERENCES "JobInstances" ("Id"),
        CONSTRAINT "FK_ReassignmentRecords_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ReassignmentRecords_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ReassignmentRecords_ScheduleAssignments_ReassignAssignmentId" FOREIGN KEY ("ReassignAssignmentId") REFERENCES "ScheduleAssignments" ("Id"),
        CONSTRAINT "FK_ReassignmentRecords_Students_NewStudentId" FOREIGN KEY ("NewStudentId") REFERENCES "Students" ("UserId"),
        CONSTRAINT "FK_ReassignmentRecords_Students_OriginalStudentId" FOREIGN KEY ("OriginalStudentId") REFERENCES "Students" ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Reviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SeniorId" integer NOT NULL,
        "SeniorFullName" text NOT NULL,
        "StudentId" integer NOT NULL,
        "StudentFullName" text NOT NULL,
        "JobInstanceId" integer NOT NULL,
        "Rating" double precision NOT NULL,
        "Comment" text,
        "RetryCount" integer NOT NULL,
        "MaxRetry" integer NOT NULL,
        "NextRetryAt" timestamp with time zone NOT NULL,
        "IsPending" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "Invoices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobInstanceId" integer NOT NULL,
        "TransactionId" integer NOT NULL,
        "MailerliteCampaignId" character varying(255),
        "InvoiceNumber" character varying(50) NOT NULL,
        "Status" integer NOT NULL,
        "DueDate" date NOT NULL,
        "SentAt" timestamp with time zone,
        "ViewedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "EmailId" integer,
        CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Invoices_InvoiceEmails_EmailId" FOREIGN KEY ("EmailId") REFERENCES "InvoiceEmails" ("Id"),
        CONSTRAINT "FK_Invoices_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Invoices_PaymentTransactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "PaymentTransactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE TABLE "JobRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderScheduleId" integer NOT NULL,
        "JobInstanceId" integer,
        "StudentId" integer NOT NULL,
        "SeniorId" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "Status" integer NOT NULL,
        "RespondedAt" timestamp with time zone,
        "RejectionReason" text,
        "SentAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "PriorityLevel" smallint NOT NULL,
        "IsReassignment" boolean NOT NULL,
        "ReassignmentRecordId" integer,
        "ReassignmentType" integer,
        "ReassignAssignmentId" integer,
        "ReassignJobInstanceId" integer,
        CONSTRAINT "PK_JobRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobRequests_JobInstances_JobInstanceId" FOREIGN KEY ("JobInstanceId") REFERENCES "JobInstances" ("Id"),
        CONSTRAINT "FK_JobRequests_OrderSchedules_OrderScheduleId" FOREIGN KEY ("OrderScheduleId") REFERENCES "OrderSchedules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobRequests_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobRequests_ReassignmentRecords_ReassignmentRecordId" FOREIGN KEY ("ReassignmentRecordId") REFERENCES "ReassignmentRecords" ("Id"),
        CONSTRAINT "FK_JobRequests_Seniors_SeniorId" FOREIGN KEY ("SeniorId") REFERENCES "Seniors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobRequests_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (1, 'Business and Economics');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (2, 'Education');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (3, 'Engineering');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (4, 'Health Sciences');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (5, 'Law');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (6, 'Medicine');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (7, 'Science');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (8, 'Social Sciences');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (9, 'Computer Science');
    INSERT INTO "Faculties" ("Id", "FacultyName")
    VALUES (10, 'Arts and Humanities');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Admin_ContactId" ON "Admin" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Cities_GooglePlaceId" ON "Cities" ("GooglePlaceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Contacts_CityId" ON "ContactInfos" ("CityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Customers_ContactId" ON "Customers" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_HNotifications_SeniorId" ON "HNotifications" ("SeniorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_HNotifications_StudentId" ON "HNotifications" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Invoices_EmailId" ON "Invoices" ("EmailId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Invoices_JobInstanceId" ON "Invoices" ("JobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Invoices_TransactionId" ON "Invoices" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_ContractId" ON "JobInstances" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_JobInstanceId" ON "JobInstances" ("JobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_OrderStatus" ON "JobInstances" ("OrderId", "Status") INCLUDE ("ScheduledDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_PrevAssignmentId" ON "JobInstances" ("PrevAssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_ScheduleAssignmentId" ON "JobInstances" ("ScheduleAssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobInstances_SeniorId" ON "JobInstances" ("SeniorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_JobInstanceId" ON "JobRequests" ("JobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_OrderId" ON "JobRequests" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_OrderScheduleId" ON "JobRequests" ("OrderScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_ReassignmentRecordId" ON "JobRequests" ("ReassignmentRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_SeniorId" ON "JobRequests" ("SeniorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_JobRequests_StudentId" ON "JobRequests" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Orders_PaymentMethodId" ON "Orders" ("PaymentMethodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Orders_SeniorId" ON "Orders" ("SeniorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Orders_ServiceId" ON "Orders" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_OrderSchedules_DayOfWeek_Start_End" ON "OrderSchedules" ("DayOfWeek", "StartTime", "EndTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_OrderSchedules_Id" ON "OrderSchedules" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_OrderSchedules_OrderId" ON "OrderSchedules" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_OrderServices_ServiceId" ON "OrderServices" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_PaymentMethods_CustomerUserId" ON "PaymentMethods" ("CustomerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_PaymentMethods_UserId" ON "PaymentMethods" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_PaymentProfiles_UserId" ON "PaymentProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_PaymentTransactions_CustomerId" ON "PaymentTransactions" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_PaymentTransactions_JobInstanceId" ON "PaymentTransactions" ("JobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_PaymentTransactions_PaymentMethodId" ON "PaymentTransactions" ("PaymentMethodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_NewStudentId" ON "ReassignmentRecords" ("NewStudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_OrderId" ON "ReassignmentRecords" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_OrderScheduleId" ON "ReassignmentRecords" ("OrderScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_OriginalStudentId" ON "ReassignmentRecords" ("OriginalStudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_ReassignAssignmentId" ON "ReassignmentRecords" ("ReassignAssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_ReassignJobInstanceId" ON "ReassignmentRecords" ("ReassignJobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ReassignmentRecords_RequestedByUserId" ON "ReassignmentRecords" ("RequestedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Reviews_JobInstanceId" ON "Reviews" ("JobInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Reviews_SeniorId" ON "Reviews" ("SeniorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Reviews_StudentId" ON "Reviews" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ScheduleAssignments_OrderScheduleId" ON "ScheduleAssignments" ("OrderScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ScheduleAssignments_Student_OrderSchedule" ON "ScheduleAssignments" ("StudentId", "OrderScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Seniors_ContactId" ON "Seniors" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Seniors_CustomerId" ON "Seniors" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_ServiceRegions_CityId_ServiceId" ON "ServiceRegions" ("CityId", "ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_ServiceRegions_ServiceId" ON "ServiceRegions" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Services_CategoryId" ON "Services" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_AvailabilitySlots_Student_Day_Time" ON "StudentAvailabilitySlots" ("StudentId", "DayOfWeek", "StartTime", "EndTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_StudentContracts_StudentId" ON "StudentContracts" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE UNIQUE INDEX "IX_Students_ContactId" ON "Students" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Students_FacultyId" ON "Students" ("FacultyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Students_Status" ON "Students" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_Students_UserId" ON "Students" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_StudentServices_ServiceId" ON "StudentServices" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    CREATE INDEX "IX_StudentServices_Student_Service" ON "StudentServices" ("StudentId", "ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Faculties"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Faculties") + 1,
            nextval(pg_get_serial_sequence('"Faculties"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015055557_InitialMigrations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251015055557_InitialMigrations', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015150712_kloInitialMigrations') THEN
    ALTER TABLE "JobInstances" DROP CONSTRAINT "FK_JobInstances_ScheduleAssignments_ScheduleAssignmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015150712_kloInitialMigrations') THEN
    ALTER TABLE "JobInstances" ALTER COLUMN "ScheduleAssignmentId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015150712_kloInitialMigrations') THEN
    ALTER TABLE "JobInstances" ADD CONSTRAINT "FK_JobInstances_ScheduleAssignments_ScheduleAssignmentId" FOREIGN KEY ("ScheduleAssignmentId") REFERENCES "ScheduleAssignments" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251015150712_kloInitialMigrations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251015150712_kloInitialMigrations', '9.0.2');
    END IF;
END $EF$;
COMMIT;

